// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa6o15lvjvVMMY82cBd1kTV-AOQLh1qWU',
    appId: '1:309607252500:web:e78174aaa828a28c3fdd01',
    messagingSenderId: '309607252500',
    projectId: 'appbarber-845d7',
    authDomain: 'appbarber-845d7.firebaseapp.com',
    storageBucket: 'appbarber-845d7.firebasestorage.app',
    measurementId: 'G-6RC0F5GYGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTAHbhePNVG7QO4yETdSGL8INMDDEu3ho',
    appId: '1:309607252500:android:a4e2419259a418413fdd01',
    messagingSenderId: '309607252500',
    projectId: 'appbarber-845d7',
    storageBucket: 'appbarber-845d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzk-vkdMkvtAviENzYsnqoUYaj5Scs-No',
    appId: '1:309607252500:ios:fb5832cef75eede03fdd01',
    messagingSenderId: '309607252500',
    projectId: 'appbarber-845d7',
    storageBucket: 'appbarber-845d7.firebasestorage.app',
    iosBundleId: 'com.example.parteMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzk-vkdMkvtAviENzYsnqoUYaj5Scs-No',
    appId: '1:309607252500:ios:fb5832cef75eede03fdd01',
    messagingSenderId: '309607252500',
    projectId: 'appbarber-845d7',
    storageBucket: 'appbarber-845d7.firebasestorage.app',
    iosBundleId: 'com.example.parteMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa6o15lvjvVMMY82cBd1kTV-AOQLh1qWU',
    appId: '1:309607252500:web:eadcc50f8c6c9e0a3fdd01',
    messagingSenderId: '309607252500',
    projectId: 'appbarber-845d7',
    authDomain: 'appbarber-845d7.firebaseapp.com',
    storageBucket: 'appbarber-845d7.firebasestorage.app',
    measurementId: 'G-K1W1P3C0HH',
  );
}
